## Lecture Notes - Randomness, Conditional Statements & Iteration ##

**Helpful Resource:**
- [Python Reference](http://data8.org/sp22/python-reference.html): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Readings:**
- [Randomness](https://inferentialthinking.com/chapters/09/Randomness.html)
- [Conditional Statements](https://inferentialthinking.com/chapters/09/1/Conditional_Statements.html)
- [Iteration](https://inferentialthinking.com/chapters/09/2/Iteration.html)


In [85]:
# import modules to be used in this notebook

from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore',category=np.VisibleDeprecationWarning)

### Randomness ###

Randomness means not intentionally to choose a particular items from a pool of things. Cherry pick is the opposite to randomness.

Randomness is an important concept in data science and many research settings.

#### `np.random.choice()` is a numpy function to simulate randomness settings ####

To use numpy functions, we need to import numpy module. `np.random.choice()` takes an array argument and simulate a random effect among the elements in the array.

In [86]:
import numpy as np

# create an array
weekday = make_array("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")

# randomly pick a week day in the week array
# np.random.choice(week) will produce different output each time it's executed
#    and each element in the array has equal chance to be selected
#    e.g. each weekday in the week array will have 1/7 of chance to be selected
np.random.choice(weekday)


'sunday'

In [87]:
# repeat the selection process 5 times
np.random.choice(weekday, 5)

array(['saturday', 'sunday', 'friday', 'thursday', 'saturday'],
      dtype='<U9')

In [88]:
# repeat the selection process 5 times again
#   the result will be different from last 5 times
np.random.choice(weekday, 5)

array(['wednesday', 'tuesday', 'friday', 'saturday', 'monday'],
      dtype='<U9')

In [178]:
# example of randomness simulation - roll a dice

# create an array with 6 faces
dice = np.arange(1, 7)

# simulate the random selection
np.random.choice(dice)

2

### Comparsion & Logical Operators ###

<img src="logical-operators.png" style="width: 500px" />

### Compare Constant Values ###

In [132]:
7 == 3.0

True

In [164]:
# Error: SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='?

7 = 7.0

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (1399794410.py, line 3)

In [135]:
a = 2
b = 7

a >= 7

False

In [136]:
6 > a < b

True

In [137]:
6 > a and a < b

True

In [140]:
9 < a * b < b - a

False

In [145]:
# using logical operator == to check the random selection result

# create an array
weekday = make_array("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")

np.random.choice(weekday) == "saturday"

True

In [146]:
day = np.random.choice(weekday)
day, day == "saturday"

('friday', False)

In [93]:
# using logical operator > to check the random selection result
np.random.choice(weekday) > "saturday"

True

In [96]:
day = np.random.choice(weekday)
day, day > "saturday"

('sunday', True)

In [78]:
months = make_array("April", "May", "June", "July", "August")
months == "September"

array([False, False, False, False, False], dtype=bool)

In [79]:
months == "June"

array([False, False,  True, False, False], dtype=bool)

In [147]:
fruits = make_array("apple", "banana", "cranberry", "apple", "cranberry", "apple")
fruits == "apple"

array([ True, False, False,  True, False,  True], dtype=bool)

In [148]:
sum(fruits == "apple")

3

In [149]:
np.count_nonzero(fruits == "apple")

3

In [150]:
np.count_nonzero(fruits == "orange")

0

In [151]:
fruits == "orange"

array([False, False, False, False, False, False], dtype=bool)

### Conditional Statements ###

Conditional statements are constructed with logical operators.

#### `if` Statement ####

In [153]:
age = 16
if age >= 16:
    print("You can drive")

You can drive


In [154]:
age = 21
if age >= 21:
    print("You can drink")

You can drink


#### `if-else` Statement ####

In [157]:
age = 10
if age >= 21:
    print("You can drive and drink")
elif age >= 16:
    print("You can drive")
else:
    print("You can do nothing yet!")

You can do nothing yet!


In [127]:
x = 2
if x > 8:
    print("true")
else:
    print("false")

false


In [159]:
def colorMatch(color):
    if color == "blue":
        return "Sky"
    elif color == "green":
        return "Apple"
    else:
        return color;

In [161]:
colorMatch("green")

'Apple'

In [162]:
colorMatch("yellow")

'yellow'

In [113]:
colorMatch(7)

7

In [124]:
def larger(arg1, arg2):
    if arg1 == arg2:
        return arg1
    elif arg1 > arg2:
        return arg1
    else:
        return arg2;

In [126]:
larger(5, 8)

8

In [125]:
larger("red", "blue")

'red'

In [128]:
larger(4.5, 8.7)

8.7

In [130]:
larger(6, 6.8)

6.8

In [163]:
# Error: TypeError: '>' not supported between instances of 'str' and 'int'

larger("sally", 10)

TypeError: '>' not supported between instances of 'str' and 'int'

### Iteration ###

Repeat a process multiple times automatically.

In [167]:
# create an array of fruit names
fruits = make_array("apple", "banana", "cranberry", "apple", "cranberry", "apple")

In [171]:
# print out each fruit using array.item() function

print(fruits.item(0))
print(fruits.item(1))
print(fruits.item(2))
print(fruits.item(3))
print(fruits.item(4))
print(fruits.item(5))

apple
banana
cranberry
apple
cranberry
apple


In [166]:
# print out each fruit in a for-loop

for my_fruit in fruits:
    print(my_fruit)

apple
banana
cranberry
apple
cranberry
apple


In [173]:
# fill up an array in a for-loop

my_numbers = make_array()

for number in np.arange(10):
    my_numbers = np.append(my_numbers, number)
    
my_numbers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [179]:
# example of randomness simulation - roll a dice

# create an array with 6 faces
dice = np.arange(1, 7)

# simulate the random selection
np.random.choice(dice)

5

In [185]:
for time in np.arange(10):
    print(np.random.choice(dice))

2
1
6
2
6
4
1
2
6
5


In [186]:
roll_result = make_array()

for time in np.arange(10):
    roll_result = np.append(roll_result, np.random.choice(dice))
    
roll_result

array([ 6.,  4.,  6.,  5.,  4.,  3.,  6.,  3.,  5.,  2.])