## Lecture Notes - Functions ##

**Helpful Resource:**
- [Python Reference](http://data8.org/sp22/python-reference.html): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Readings:**
- [Functions and Tables](https://inferentialthinking.com/chapters/08/Functions_and_Tables.html)
- [Applying a Function to a Column](https://inferentialthinking.com/chapters/08/1/Applying_a_Function_to_a_Column.html)
- [Visualization](https://inferentialthinking.com/chapters/07/Visualization.html)

In [17]:
# import modules to be used in this notebook

from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## The Anatomy of a Function ## 

<img src="functions-anatomy-1.png" style="width: 500px" />

A -- Signature

B -- Documentation ("docstring")

C -- Body

E -- Indentation

<hr>

### Name, Arguments/Parameters, Statements & Return Values ###
<img src="functions-anatomy-2.png" style="width: 500px" />

## Functions Operations ##

In [18]:
def double(x):
    """ Take one argument x, multiple x by 2 and return the value"""
    return 2*x

In [19]:
# Documentation explain what the function does and how to use it

# display the function documentation
double?

In [20]:
# Multiple statements in a function body

def double(x):
    """ Take one argument x, multiple x by 2 and return the value"""
    timeTwo = 2 * x
    return timeTwo

### Functions are Type-Agnostic ###

Functions operate on any data types based on the arguments passed into it.

In [21]:
# int

double(5)

10

In [22]:
# string

double("sally ")

'sally sally '

In [23]:
# float

double(4.7)

9.4

### Multiple Arguments in a Function ###

Functions can take more than one argument.

In [24]:
def volumn(width, height, depth):
    """ Take three argunment, compute and return the volumn """
    vol = width * height * depth
    return vol

In [25]:
volumn(2, 3, 4)

24

### Functions operate on an array ###

Functions can take an array argument and operate on each element in the array.

In [26]:
# Take an array argument and return an array with updated values in it.
def double(x):
    """ Take one argument x, multiple x by 2 and return the value"""
    return 2*x

num_array = make_array(2, 4, 6)

double(num_array)

array([ 4,  8, 12])

In [27]:
# Example to take an array of float argument

double(make_array(2.5, 4.6, 6.7))

array([  5. ,   9.2,  13.4])

In [28]:
# Example to take multiple arrays and operate on each element of the arrays

def volumn(width, height, depth):
    """ Take three argunment, compute and return the volumn """
    vol = width * height * depth
    return vol

width = make_array(1,2,3)
height = make_array(4,5,6)
depth = make_array(7,8,9)

volumn(width, height, depth)

array([ 28,  80, 162])

## Functions Scope ##

Names/variables that are inside a function or the function argument araa can only be seen by the function itself. It is call local scope.

In [29]:
def volumn(f_width, f_height, f_depth):
    """ Take three argunment, compute and return the volumn """
    vol = f_width * f_height * f_depth
    return vol

my_width = make_array(1,2,3)
my_height = make_array(4,5,6)
my_depth = make_array(7,8,9)

volumn(my_width, my_height, my_depth)

array([ 28,  80, 162])

In [53]:
# Error: because f_width can only be accessed inside the function volumn
f_width

NameError: name 'f_width' is not defined

## Apply a Function to a Column in a Table ##

Now we know functions can take an array argument. Functions can also be applied to a column in a table and return an array with updated values.


In [49]:
# Create a table from scratch with arrays and columns

names = make_array("apple", "banana", "cranberry")
prices = make_array(1.2, 0.29, 3.2)

fruits = Table().with_columns(
        "Fruit", names,
        "Price", prices
)

fruits

Fruit     | Price
apple     | 1.2
banana    | 0.29
cranberry | 3.2

In [50]:
# Create a function to double a price

def doublePrice(x):
    """ Take one argument x, multiple x by 2 and return the value"""
    newPrice = 2 * x
    return newPrice

fruits.apply(doublePrice, "Price")

array([ 2.4 ,  0.58,  6.4 ])

In [51]:
fruits

Fruit     | Price
apple     | 1.2
banana    | 0.29
cranberry | 3.2

In [52]:
# Create a new table to include the new price column and
#   rename the original price column name to "Old Price"

new_prices = fruits.with_columns("New Price", fruits.apply(doublePrice, "Price")).relabeled("Price", "Old Price")
new_prices

Fruit     | Old Price | New Price
apple     | 1.2       | 2.4
banana    | 0.29      | 0.58
cranberry | 3.2       | 6.4

In [48]:
new_prices.group("Fruit", np.average)

Fruit     | Old Price average | New Price average
apple     | 1.05              | 2.1
banana    | 0.245             | 0.49
cranberry | 3.7               | 7.4